version: "3"

services:
  swayswap-fuel-core:
    container_name: "swayswap-fuel-core-${ENVIRONMENT:-development}"
    environment:
      MIN_GAS_PRICE: ${GAS_PRICE}
      # This is the private key of the consensus.PoA.signing_key in the chainConfig.json
      # this key is responsible for validating the transactions
      CONSENSUS_KEY: 0xa449b1ffee0e2205fa924c6740cc48b3b473aa28587df6dab12abc245d1f5298
    build: ./fuel-core
    ports:
      - "${FUEL_CORE_PORT:-4000}:4000"
    volumes:
      - swayswap-fuel-core-db:/mnt/db
    healthcheck:
      test: curl --fail http://localhost:4000/health || exit 1
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  swayswap-fuel-core-db:
    name: "fuel-core-db-${ENVIRONMENT:-development}"
