[project]
author = "devel"
entry = "main.sw"
license = "Apache-2.0"
name = "swayswap"

[dependencies]
core = { git = "http://github.com/FuelLabs/sway-lib-core" }
std = { git = "http://github.com/FuelLabs/sway-lib-std" }
